-- MySQL Script generated by MySQL Workbench
-- Mon Feb 14 15:46:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema omajdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `omajdb` ;

-- -----------------------------------------------------
-- Schema omajdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `omajdb` DEFAULT CHARACTER SET utf8 ;
USE `omajdb` ;

-- -----------------------------------------------------
-- Table `omajdb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `omajdb`.`category` ;

CREATE TABLE IF NOT EXISTS `omajdb`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omajdb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `omajdb`.`brand` ;

CREATE TABLE IF NOT EXISTS `omajdb`.`brand` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`brand_id`),
  UNIQUE INDEX `brand_id_UNIQUE` (`brand_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omajdb`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `omajdb`.`color` ;

CREATE TABLE IF NOT EXISTS `omajdb`.`color` (
  `color_id` INT NOT NULL AUTO_INCREMENT,
  `color_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`color_id`),
  UNIQUE INDEX `color_id_UNIQUE` (`color_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omajdb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `omajdb`.`product` ;

CREATE TABLE IF NOT EXISTS `omajdb`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_price` DECIMAL(5,2) NOT NULL,
  `product_img` VARCHAR(255) NULL,
  `product_category` INT NOT NULL,
  `product_brand` INT NOT NULL,
  `product_color` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  INDEX `fk_product_category_idx` (`product_category` ASC) VISIBLE,
  INDEX `fk_product_brand1_idx` (`product_brand` ASC) VISIBLE,
  INDEX `fk_product_color1_idx` (`product_color` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`product_category`)
    REFERENCES `omajdb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`product_brand`)
    REFERENCES `omajdb`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_color1`
    FOREIGN KEY (`product_color`)
    REFERENCES `omajdb`.`color` (`color_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omajdb`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `omajdb`.`size` ;

CREATE TABLE IF NOT EXISTS `omajdb`.`size` (
  `size_id` INT NOT NULL AUTO_INCREMENT,
  `size_value` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`size_id`),
  UNIQUE INDEX `size_id_UNIQUE` (`size_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omajdb`.`product_has_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `omajdb`.`product_has_size` ;

CREATE TABLE IF NOT EXISTS `omajdb`.`product_has_size` (
  `product_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `size_id`),
  INDEX `fk_product_has_size_size1_idx` (`size_id` ASC) VISIBLE,
  INDEX `fk_product_has_size_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_size_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `omajdb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_size_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `omajdb`.`size` (`size_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `omajdb`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `omajdb`;
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'dress');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'top');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'shoes');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'socks');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'underwear');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'pants');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'hat');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'shirt');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 'coat');
INSERT INTO `omajdb`.`category` (`category_id`, `category_name`) VALUES (DEFAULT, 't-shirt');

COMMIT;


-- -----------------------------------------------------
-- Data for table `omajdb`.`brand`
-- -----------------------------------------------------
START TRANSACTION;
USE `omajdb`;
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Adidas');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Armani');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Bonpoint');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Berenice');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'COS');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Comptoir des Cotonniers');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Dickies');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Devred');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Etam');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Gucci');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Homecore');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'IKKS');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Jules');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Kenzo');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Levi\'s');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Maje');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Muji');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Petit Bateau');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Sandro');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Super Dry');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'Uniqlo');
INSERT INTO `omajdb`.`brand` (`brand_id`, `brand_name`) VALUES (DEFAULT, 'The Kooples');

COMMIT;


-- -----------------------------------------------------
-- Data for table `omajdb`.`color`
-- -----------------------------------------------------
START TRANSACTION;
USE `omajdb`;
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'black');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'white');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'red');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'purple');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'orange');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (, 'yellow');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'green');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'blue');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'brown');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'gold');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'silver');
INSERT INTO `omajdb`.`color` (`color_id`, `color_name`) VALUES (DEFAULT, 'pink');

COMMIT;


-- -----------------------------------------------------
-- Data for table `omajdb`.`product`
-- -----------------------------------------------------
START TRANSACTION;
USE `omajdb`;
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Long dress', 28.5, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/PhotoRoom_20210713_152314_6ae6326b-5e8f-4d4c-81cf-6a1b95e028a1_grande.jpg?v=1644622839', 1, 6, 1);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Long dress', 35.6, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/PhotoRoom_20210713_153006_3d83a550-77e6-41e6-9818-43aa7f476dad_grande.jpg?v=1644622737', 1, 6, 12);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Long dress', 26.9, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/B23m4P8xJxI5_grande.jpg?v=1644570556', 1, 9, 1);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Velvet shirt', 35.4, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/sQ5ePxWRA83b_25dded4c-f086-44bc-a6fc-b7d83e204678_grande.jpg?v=1644802335', 8, 6, 9);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Silk shirt', 45.9, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/TVN9R9gX4mSb_grande.jpg?v=1644570992', 8, 6, 1);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Silk shirt', 42.5, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/PhotoRoom_20210720_230537_grande.jpg?v=1644624175', 8, 9, 12);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Silk dress', 58.2, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/1627461353218_7490167260149095757_grande.jpg?v=1644625542', 1, 9, 9);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Coton shirt', 26.3, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/2021-07-2811_32_39_grande.jpg?v=1644625654', 8, 6, 1);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Shirt', 22.9, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/1627465361803_1705869119289019102_grande.jpg?v=1644625681', 8, 3, 9);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Silk shirt', 32.85, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/2021-07-2811_48_06_grande.jpg?v=1644625698', 8, 9, 9);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Shirt', 23.5, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/1627465731315_2647328194508186988_grande.jpg?v=1644625689', 8, 6, 1);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Flower top', 12.8, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/VUFz1Zrcf5q1_grande.jpg?v=1644804107', 2, 6, 3);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Top', 15.6, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/xHaZWpK1huNd_grande.jpg?v=1644804043', 2, 9, 6);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Short dress', 35.9, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/1627480486315_5854905902285717000_grande.jpg?v=1644625855', 1, 6, 9);
INSERT INTO `omajdb`.`product` (`product_id`, `product_name`, `product_price`, `product_img`, `product_category`, `product_brand`, `product_color`) VALUES (DEFAULT, 'Dress', 36.9, 'https://cdn.shopify.com/s/files/1/0577/1421/3034/products/7LCPGqRjCIzM_grande.jpg?v=1644803980', 1, 5, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `omajdb`.`size`
-- -----------------------------------------------------
START TRANSACTION;
USE `omajdb`;
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '34 / XS');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '36 / S');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '38 / M');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '40 / L');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '42 / XL');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '44 / XXL');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '46 / XXL');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '48 / XXXL');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '');
INSERT INTO `omajdb`.`size` (`size_id`, `size_value`) VALUES (DEFAULT, '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `omajdb`.`product_has_size`
-- -----------------------------------------------------
START TRANSACTION;
USE `omajdb`;
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (1, 2);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (1, 3);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (1, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (1, 5);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (2, 6);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (2, 8);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (3, 2);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (3, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (3, 6);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (4, 2);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (4, 5);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (4, 8);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (5, 3);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (5, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (6, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (7, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (7, 5);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (7, 6);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (8, 3);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (8, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (9, 5);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (9, 7);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (9, 8);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (9, 1);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (9, 2);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (9, 3);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (10, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (11, 5);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (11, 6);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (12, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (12, 5);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (12, 8);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (13, 3);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (13, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (13, 6);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (14, 2);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (14, 3);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (14, 4);
INSERT INTO `omajdb`.`product_has_size` (`product_id`, `size_id`) VALUES (15, 5);

COMMIT;

